spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/account_system?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: sa

mybatis:
  type-aliases-package: com.example.demo.bean
  mapper-locations: classpath:mapper/*.xml


server:
  port: 8089

logging:
  level:
    com.example.demo.dao : debug